### ISSUE TITLE
Add python basic programs

### ISSUE THREAD

**Issue by Aayush-hub** [Aayush-hub/Basic-Python-programs#1]
Add more creative and basic python programs for practice in existing repository.

**Comment by Mayank662** [comment]
Hi @Aayush-hub I would like work on this task.

**Comment by Sai-Nikhita** [comment]
Hi, @Aayush-hub I would like to work on this.

**Comment by Nikzy7** [comment]
Hey There! Just created a PR for Offline Text-To-Speech script.. Do have a look! Pretty easy and useful for basic as well as professional projects.

**Comment by karuna-sth** [comment]
Hey, @Aayush-hub Can I contribute on this?

**Comment by amitsat27** [comment]
hey @Aayush-hub can i contribute ?

**Comment by Nikzy7** [comment]
Hey ! Check out my PR #14 .

**Comment by bratinkundu** [comment]
Please check my PR, #6

**Comment by kkkkkabir** [comment]
Hey! I would like to work on this.

**Comment by anuragdevon** [comment]
Heya! Just added a PR. Once check it out and I would enjoy to work on this.

**Comment by punitaojha** [comment]
Hey @Aayush-hub I would like to work on this issue.

**Comment by kkkkkabir** [comment]
@Aayush-hub Consider changing the "Hacktoberfest" tag to "hacktoberfest" with a small *h* as the pull requests are not being considered eligible for the event.  The site is recommending to use the "hacktoberfest" tag for participation.

**Comment by Nikzy7** [comment]
> Hey ! Check out my PR #14 .

@Aayush-hub take a look at this one 😄

**Comment by geekyboy14** [comment]
@Aayush-hub Check the PR #22 I have added two good python programs

**Comment by Lakshit-Chiranjiv** [comment]
hey....i added a program to convert a sentence to its piglatin form using python....please merge it...it is working fine....PR #31

**Comment by Lakshit-Chiranjiv** [comment]
please also add a hacktoberfest-accepted label to it....thankyou...PR #31

**Comment by poochingil** [comment]
I would like to work on this issue.
Can you please check my PR for any changes?
I have added a program to find the roots of a quadratic equation.
