### ISSUE TITLE
Update readme for better understandings.

### ISSUE THREAD

**Issue by Aayush-hub** [Aayush-hub/Basic-Python-programs#5]
Update readme for better understandings of programs and new concepts.

**Comment by withlovedese** [comment]
What would you like to see in the updated readme? What sort of programs are you expecting?

**Comment by Aayush-hub** [comment]
Star this repository.

**Comment by withlovedese** [comment]
I'm sorry I'm still confused lol. Would you want me to give like instructions about how to add to the repository or  what sort of programs that could be submitted (with examples) or should i just say they should star the repository lol?

**Comment by Aayush-hub** [comment]
Basic python programs for beginers for practice and better understanding of python will be added to this repo. You have to describe what this repo is for and the steps included to contribute in this repo for new peers.
